name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: huantt/pacman-contribution-graph@v1.0.0
        with:
          github-username: http-pruthvi
          ghp-token: ${{ secrets.GITHUB_TOKEN }}
          output-folder: dist

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
